version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./app/.env

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
