"""rename field from task_name to name

Revision ID: d2c32e11dfaa
Revises: fa10caac5fa1
Create Date: 2024-09-16 19:54:26.861705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c32e11dfaa'
down_revision: Union[str, None] = 'fa10caac5fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_name', new_column_name='name', existing_type=sa.String(length=80), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'name', new_column_name='task_name', existing_type=sa.String(length=80), existing_nullable=False)
    # ### end Alembic commands ###
