"""add role manager

Revision ID: fa10caac5fa1
Revises: c6503a8c5e5e
Create Date: 2024-09-15 18:16:21.238259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa10caac5fa1'
down_revision: Union[str, None] = 'c6503a8c5e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE 'MANAGER';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole DROP VALUE 'MANAGER';")
    # ### end Alembic commands ###
